package:
  name: tmx_cpp_py
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script_env:
    - MACOSX_DEPLOYMENT_TARGET="10.15" # [osx]
  #   - Boost_INCLUDE_DIR={{ CONDA_PREFIX }}/include/boost
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - "{{ stdlib('c') }}"
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja
    - boost-cpp ==1.74.0
    - libtool # [osx]

  host:
    - python
    - pip !=22.1.0

  run:
    - python


test:
  requires:
    - pytest
  imports:
    - tmx_cpp_py
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: Python Bindings for tmx-cpp with pybind11.
  license_file: LICENSE
