name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-12]
        python-version: ["3.8", "3.10"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: strict

      # Currently conda-build requires the dead package "toml" but doesn't declare it
      - name: Prepare
        run: conda install conda-build conda-verify pytest toml

      # - name: Install Extra Deps (Ubuntu)
      #   if: ${{ runner.os == 'Linux' }}
      #   run: sudo apt install -y libboost-all-dev

      # - name: Install Extra Deps (Windows)
      #   if: ${{ runner.os == 'Windows' }}
      #   run: |
      #     nuget install boost -Version 1.74.0

      - name: Build
        run: conda build conda.recipe

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ tmx_cpp_py

      - name: Test
        run: python -m pytest
