name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-13, ubuntu-latest]
        python-version: ["3.8", "3.10", "3.12"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Install Dependencies (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install libboost-all-dev

    - name: Install Dependencies (MacOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install boost

    - name: Install Dependencies (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        nuget install boost -Version 1.74.0

    # - name: Install boost (Windows)
    #   uses: MarkusJx/install-boost@v2.4.5
    #   if: ${{ runner.os == 'Windows' }}
    #   id: install-boost
    #   with:
    #       # REQUIRED: Specify the required boost version
    #       # A list of supported versions can be found here:
    #       # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
    #       boost_version: 1.74.0

    # - name: Setup Boost (Windows)
    #   if: ${{ matrix.platform }} == windows-latest
    #   run:

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: python -m pytest
