name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.5
      if: ${{ runner.os == 'Windows' }} # || runner.os == 'macOS'
      id: install-boost
      with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.74.0
          # platform_version: ${{ os.version }}

    - uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_ARCHS_MACOS: auto universal2
        CIBW_ARCHS_LINUX: auto64 aarch64 ppc64le s390x
        CIBW_ENVIRONMENT_WINDOWS: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'
        CIBW_ENVIRONMENT_MACOS: BOOST_ROOT={package}/boost
        CIBW_BEFORE_BUILD_LINUX: echo $BOOST_ROOT
        CIBW_BEFORE_ALL_LINUX: >
          dnf -y install wget &&
          cd / &&  mkdir boost && cd boost &&
          wget --no-check-certificate 'https://sourceforge.net/projects/boost/files/boost/1.74.0/boost_1_74_0.tar.bz2' &&
          tar xf boost_1_74_0.tar.bz2 &&
          cd boost_1_74_0 && mkdir lib && cd tools/build && ./bootstrap.sh && cd - && ./tools/build/b2 install &&
          cd {package}
        CIBW_BEFORE_ALL_MACOS: >
          brew install wget &&
          cd {package} &&  mkdir boost && cd boost &&
          wget --no-check-certificate 'https://sourceforge.net/projects/boost/files/boost/1.74.0/boost_1_74_0.tar.bz2' &&
          tar xf boost_1_74_0.tar.bz2 &&
          cd boost_1_74_0 && mkdir lib && cd tools/build && ./bootstrap.sh && cd - && ./tools/build/b2 install  &&
          cd {package}
        CIBW_TEST_COMMAND: python -m pytest --rootdir={package} {package}/tests
        CIBW_TEST_REQUIRES: pytest
        CIBW_ENVIRONMENT_LINUX: BOOST_ROOT=/boost
        CIBW_ENVIRONMENT_PASS_LINUX: BOOST_ROOT

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: wheelhouse/*.whl


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_password }}
